### ISSUE TITLE
Change color of navbar 

### ISSUE THREAD

**Issue by rogargon** [DJovellar/Videoadiccio#2]
From current blue to a more standard grey, like Bootstrap's default

**Comment by DJovellar** [comment]
But the background color of the session is already the default gray of Bootstrap, so the navbar will not be seen.

When applying this change, it looks like this.

![navbar-color](https://user-images.githubusercontent.com/47555490/99999154-04a7ab00-2dc0-11eb-98a4-0edd4c581e4a.PNG)

**Comment by rogargon** [comment]
You can use navbar-dark:

```
<nav class="navbar navbar-dark bg-dark">
  <!-- Navbar content -->
</nav>
```

https://getbootstrap.com/docs/4.0/components/navbar/#color-schemes

**Comment by DJovellar** [comment]
Done!

**Comment by rogargon** [comment]
👍
