### ISSUE TITLE
Text for the presentation page

### ISSUE THREAD

**Issue by rogargon** [DJovellar/Videoadiccio#3]
### Adicción a los videojuegos

Según el [Instituto Superior de Estudios Psicológicos](https://www.isep.es/actualidad-psicologia-clinica/adiccion-videojuegos/) cada vez son más los niños y jóvenes que juegan a videojuegos y que, como consecuencia de su uso incorrecto, acaban convirtiéndose en adictos a ellos.

Tanto es así, que en 2018, debido a esta creciente problemática,  la Organización Mundial de la Salud (OMS), catalogó la adicción a los videojuegos como un desorden de salud mental, incluyéndolo dentro del apartado relacionado con los desórdenes adictivos de la Clasificación Internacional de Enfermedades.

Esta aplicación permite reflexionar sobre los mecanismos diseñados para engancharnos y ver qué riesgos se pueden correr, de forma que se puedan encontrar mecanismos para devolver el control.

**Comment by DJovellar** [comment]
Done!

**Comment by rogargon** [comment]
Looks really nice! 👏
